###

# curl -X POST http://localhost:8080/api/books
#  -H "Content-Type: application/json"
#  -d '{
#    "title": "Clean Code",
#    "author": "Robert C. Martin",
#    "isbn": "978-0132350884",
#    "publisher": "Prentice Hall",
#    "publishYear": 2008
#  }'
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "isbn": "0-306-40615-2",
  "publisher": "Prentice Hall",
  "publishYear": 2008
}

###
# curl http://localhost:8080/api/books/available
GET http://localhost:8080/api/books/available

###
# curl -X POST http://localhost:8080/api/books
#  -H "Content-Type: application/json"
#  -d '{
#    "title": "",
#    "author": "R",
#    "isbn": "invalid"
#  }'
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "",
  "author": "",
  "isbn": "0-306-40615-2"
}

###

# curl http://localhost:8080/api/books/999
GET http://localhost:8080/api/books/999

###

# curl -X POST http://localhost:8080/api/auth/register
#  -H "Content-Type: application/json"
#  -d '{
#    "email": "jan.kowalski@example.com",
#    "password": "Password123!",
#    "firstName": "Jan",
#    "lastName": "Kowalski"
#  }'
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "jan.kowalski@example.com",
  "password": "Testing193@",
  "firstName": "Jan",
  "lastName": "Kowalski"
}

###

# curl -X POST http://localhost:8080/api/auth/login
#  -H "Content-Type: application/json"
#  -d '{
#    "email": "jan.kowalski@example.com",
#    "password": "Password123!"
#  }'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "jan.kowalski@example.com",
  "password": "Testing193@"
}

###
# curl http://localhost:8080/api/loans
GET http://localhost:8080/api/loans

###

# curl http://localhost:8080/api/loans
#  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..."
GET http://localhost:8080/api/loans
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...

###






